### ISSUE TITLE
after closing vscode, the plugin still runs

### ISSUE THREAD

**Issue by bobzhang** [rescript-lang/rescript-vscode#43] opened 2020-12-07 12:32 UTC
platform: windows.
I closed vscode, the editor plugin is not reclaimed and it seems there are lots of such processes running
![BUG](https://user-images.githubusercontent.com/747051/101351198-31cd8080-38cb-11eb-8f0e-0198c612d794.PNG)

**Comment by chenglou** [comment] 2021-01-29 09:24
@johnny88 @mewhhaha sorry for the ping; this seems to happen to more than one person. Do you guys get this?

**Comment by mewhhaha** [comment] 2021-01-29 09:48
👍 I had this issue as well, but I started running bsb -w manually instead of relying on the plugin.

**Comment by chenglou** [comment] 2021-01-29 09:49
This shouldn't be related to `bsb -w` at all though; this is a different binary, called `rescript-editor-support`

**Comment by mewhhaha** [comment] 2021-01-29 09:51
Hm, maybe I had a different issue, then. I just remember having several processes running after restarting vs code several times. I will check if it's the same process that's persisting.

**Comment by johnny88** [comment] 2021-01-29 10:57
I tried it and I don't get that process in the task manager at all. Very odd.

**Comment by johnny88** [comment] 2021-01-29 11:00
Just to test I tried running the exe itself and that seems to run fine. It shows up in the task manager. Not sure what's going on. Could it be that the process is hidden by vscode itself? One of it's sub-processes.

**Comment by chenglou** [comment] 2021-01-29 11:02
That binary is spawn then should die; is that what you see?

**Comment by johnny88** [comment] 2021-01-29 11:17
I am actually seeing the opposite problem, that the binary isn't launching at all. I'm attempting to debug now.

**Comment by johnny88** [comment] 2021-01-29 11:18
![Screen Shot 2021-01-29 at 12 17 52](https://user-images.githubusercontent.com/6550688/106268908-0a8c9300-622c-11eb-8ed9-8f469b1a72f8.png)

**Comment by johnny88** [comment] 2021-01-29 11:38
When I ran the command run in the runDumpCommand the executable runs for a moment then disappears. It runs as a subprocess of the command prompt I'm running. I haven't been able to see this process spin up in the context of vscode but I can say for sure that it's not adding anything at route level.

**Comment by johnny88** [comment] 2021-01-29 11:44
I also can see it as a part of the node instances running (which I am assuming is the server instance)

**Comment by chenglou** [comment] 2021-01-29 13:08
cc @ruifortes from https://github.com/rescript-lang/rescript-editor-support/issues/53
Are you still able to repro this? That closing vscode doesn't terminate the process `rescript-editor-support`? I'm wondering whether the binary is hanging on some calculations.
cc @cristianoc

**Comment by mewhhaha** [comment] 2021-01-29 14:24
I was not able to reproduce my issue.

**Comment by ruifortes** [comment] 2021-01-29 15:47
@chenglou yep. Just had to manually end dozens of processes ten minutes ago.
By the way... sometimes, right after launching build, it throws over permission denied for .sourcedirs.json but deleting the lib folder solves it.
Could it be related?

**Comment by ruifortes** [comment] 2021-01-29 16:26
also... how to disable the constant "Start a build for this project to get the freshest data?"
I don't use it but don't know where to disable it

**Comment by cristianoc** [comment] 2021-01-29 17:10
@ruifortes is there a self-contained project to reproduce the issue with the processes consistently?

**Comment by ruifortes** [comment] 2021-01-29 21:32
@cristianoc it start spawning as soon as I start typing in a .res file
I'll reinstall it... I'm ashamed to admit I didn't do it already :-P

**Comment by chenglou** [comment] 2021-01-30 00:56
@ruifortes Can you also show me a video of what that build alert looks like? It should onyx activate when you open the first file of a project

**Comment by ruifortes** [comment] 2021-01-30 22:40
@chenglou I just reinstalled the plugin and very fast it spawn a dozen processes and CPU at 100% :-(
I'll see if the the build error reapears.
And also...wtf is onyx :-P

**Comment by cristianoc** [comment] 2021-01-31 09:31
@ruifortes thanks, let's see if we get closer to a culprit.
Does it happen when you only hover on the code without editing? Does it show type information?
And if you add an empty file to the project and start editing, does it happen?

**Comment by bobzhang** [comment] 2021-02-02 06:12
Testing again on version  rescript-vscode 1.0.4, windows, vscode 1.52.1, bs-platform@8.4.2

- auto completion: works
- hover show types: works
-  go to definition across files: not work
error message:
```
Unable to open 'hello.res': Unable to read file '\\c:\Users\hongbozhang\test-ide\src\hello.res' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat '\\c:\Users\hongbozhang\test-ide\src\hello.res').
```
```
Unable to open 'list.mli': Unable to read file '\\c:\Users\hongbozhang\test-ide\node_modules\bs-platform\lib\ocaml\list.mli' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat '\\c:\Users\hongbozhang\test-ide\node_modules\bs-platform\lib\ocaml\list.mli').
```
but we do have these files:
```
PS C:\Users\hongbozhang\test-ide\src> ls 


    Directory: C:\Users\hongbozhang\test-ide\src


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          2021/2/2     14:03             64 hello.res
-a----          2021/2/2     14:02             40 xx.res
```
- go to definition to the std: not work
- go to definition in the same file: work
- error diagnostics: not work
- when open just one window: lots of code.exe process, see the pic below, when it is closed, those processes are gone, so it seems this is a bug of vscode, may already be fixed in upstream
<img width="534" alt="捕获" src="https://user-images.githubusercontent.com/747051/106559609-98d08400-6560-11eb-8a7a-c7f1c97c9738.PNG">

**Comment by chenglou** [comment] 2021-02-02 07:25
Seems like Cristiano's binary has some cross-platform path logic bug

**Comment by chenglou** [comment] 2021-02-03 08:45
New version released. Feel free to upgrade and see if some of these repro! Thanks

**Comment by chenglou** [comment] 2021-03-13 03:43
Aaaalright since nobody's been replying then I'll assume it's fixed =)
Feel free to ping if it's not! Thanks again for all the help everyone

**Closed by chenglou** 2021-03-13 03:43 UTC
