### ISSUE TITLE
No hover type hint for variables

### ISSUE THREAD

**Issue by sym233** [rescript-lang/rescript-vscode#550] opened 2022-08-12 04:02 UTC
![image](https://user-images.githubusercontent.com/10321547/184281262-3b7fe560-dc26-4d69-af7c-c8996a33e336.png)
I think there should be a hint, e.g. greeting is string, but nothing poped up.

It can auto-complete `external` keyword as expected.
![image](https://user-images.githubusercontent.com/10321547/184282119-8cb5253c-d390-459e-bea7-443cba6b59ef.png)

Rescript compiler works properly.
![image](https://user-images.githubusercontent.com/10321547/184282653-5ffcd880-b7ec-4b8c-b34f-52aab65f88be.png)

I'm new to rescript and not sure I installed the extension properly. I use yarn 2 thus no `node_modules` in the working directory, and find executables in `.yarn` subdirectory.

vscode `setting.json`:
```json
{
    "rescript.settings.binaryPath": "[proj_name]\\.yarn\\unplugged\\rescript-npm-9.1.4-75c65d01e7\\node_modules\\rescript",
    "rescript.settings.autoRunCodeAnalysis": true
}
```

`bsconfig.json`:
```json
{
  "name": "proj_name",
  "sources": [
    {
      "dir": "src",
      "subdirs": true
    }
  ],
  "package-specs": [
    {
      "module": "es6",
      "in-source": true
    }
  ],
  "suffix": ".bs.js",
  "bs-dependencies": []
}
```
`package.json`:
```json
{
  "name": "proj_name",
  "packageManager": "yarn@3.2.2",
  "devDependencies": {
    "rescript": "^9.1.4"
  },
  "scripts": {
    "re:build": "rescript",
    "re:start": "rescript build -w"
  }
}
```

System info:
版本: 1.70.1 (user setup)
提交: 6d9b74a70ca9c7733b29f0456fd8195364076dda
日期: 2022-08-10T06:08:33.642Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

extension version: v1.4.2

**Comment by cristianoc** [comment] 2022-08-12 05:06
Make sure the file was saved before trying to hover.
If it was saved, start with an empty project that only contains those 2 lines, se if the issue is still there.

**Comment by sym233** [comment] 2022-08-12 05:50
The file was saved.

I did other trials
- clone https://github.com/rescript-lang/rescript-project-template
- `yarn` # install, using yarn 1 here, with `node_modules`
- leave "rescript.settings.binaryPath" empty
Then the hover hint appears.

- clone template again
- `yarn set version berry` # swap to yarn 2, plug'n'play
- `yarn -v` # 3.2.2
- `yarn` # install without node_modules
- set "rescript.settings.binaryPath" to "D:\\Github\\rescript-project-template\\.yarn\\unplugged\\rescript-npm-9.1.4-75c65d01e7\\node_modules\\rescript"
- click 'build' in the popup
Then no hover hint.

Maybe the extension cannot resolve that binary path, or not compatible with yarn 2?

**Comment by cristianoc** [comment] 2022-08-12 06:32
We have no windows devs, so these are always tricky.
It would be good to at some point have someone who can build the extension from source on Windows and begin debugging these very basic cases.

**Comment by zth** [comment] 2022-08-12 06:39
Can you try the pre-release version of the extension?

**Comment by sym233** [comment] 2022-08-12 06:43
> Can you try the pre-release version of the extension?

nothing changes

**Comment by sym233** [comment] 2022-08-12 07:16
I tested it in wsl with yarn 2. NO hover hint still.

> * clone template again
> * `yarn set version berry` # swap to yarn 2, plug'n'play
> * `yarn -v` # 3.2.2
> * `yarn` # install without node_modules
> * set "rescript.settings.binaryPath" to "D:\Github\rescript-project-template\.yarn\unplugged\rescript-npm-9.1.4-75c65d01e7\node_modules\rescript"
> * click 'start build' in the popup
>   Then no hover hint.

**Comment by fhammerschmidt** [comment] 2022-08-12 07:52
Before we have a fix, can you try https://github.com/reason-seoul/yarn-plugin-rescript and check if the extension works with that?

**Comment by sym233** [comment] 2022-08-12 10:43
@fhammerschmidt it seems to have issue, too.
https://github.com/reason-seoul/yarn-plugin-rescript/issues/14

**Comment by fhammerschmidt** [comment] 2022-08-12 10:50
Ok, I guess the plugin is not compatible with Windows (or your setup).

Alternatively: 
Can you set `nodeLinker` to `node-modules` in your `.yarnrc.yml`?
See: https://yarnpkg.com/configuration/yarnrc#nodeLinker

Then the extension should work without setting the binary path manually. However it disables pnp.

**Comment by sym233** [comment] 2022-08-12 10:59
@fhammerschmidt ah, that works

**Comment by fhammerschmidt** [comment] 2022-08-12 12:14
Just to clarify: It does not make sense for the extension to support yarn PnP yet, when even the compiler does not: https://github.com/rescript-lang/rescript-compiler/issues/3276

As soon as you add some dependencies, you will have all kinds of issues.

**Comment by zth** [comment] 2023-02-01 06:56
Closing this since there's nothing actionable for us here for now.

**Closed by zth** 2023-02-01 06:56 UTC
