### ISSUE TITLE
Some regexes cause error message in vscode about forgetting commas

### ISSUE THREAD

**Issue by tmepple** [rescript-lang/rescript-vscode#359] opened 2022-02-05 14:27 UTC
Trying to convert some old working .re code into .res format and ran into an error in vscode.

```
let humanize = fieldName =>
  fieldName
  |> Js.String.replaceByRe(%re("/([A-Z])/g"), " $1")
  |> Js.String.replaceByRe(%re("/\\_/g"), " ")
  |> Js.String.toLowerCase
  |> Js.String.trim
```

The first regex in this pipeline gives a "Did you forget a ',' here?" error message but works in [the playground](https://rescript-lang.org/try?code=DYUwLgBAFgrgtgQwHYEsBeIIF4IDMUjAAmAcgnJlgHwQBQEeBxZF9EAPjQFIDOAdAGUwAJxRIA5n2EgADsAQBjEACEAngCUQACgCk0rQCIA9FoDaAQQC0ALQC6ASiPiD9gDQQDEACQBGF204IXkERMUlpOUUVDW09bWMAHQSAfScXd09-BkDgoVEJPjAAewAZIoB3EGEAYQQeEADufjywwtE4IA)

ReScript v9.1.4
latest vscode plugin v1.2.

<img width="482" alt="Screen Shot 2022-02-05 at 9 16 31 AM" src="https://user-images.githubusercontent.com/1711033/152645729-672209fd-f2dc-451e-a8fb-694357ddf220.png">
1

**Comment by zth** [comment] 2022-03-20 19:12
I cannot seem to reproduce this. Is this still the case with the latest versions of everything - the extension, the ReScript package, etc?

**Comment by zth** [comment] 2022-03-22 08:31
Closing this since neither me nor @cristianoc can reproduce. Please feel free to open again if you still can reproduce!

**Closed by zth** 2022-03-22 08:31 UTC

**Comment by tmepple** [comment] 2022-03-26 19:29
Thanks so much for looking at this.  It was really weird but when I opened vscode today there was a dialog box saying something about "rebuilding" the environment.  I clicked OK then these errors went away and it's working now.
