### ISSUE TITLE
Autocomplete does not work with pipes

### ISSUE THREAD

**Issue by Lomand** [rescript-lang/rescript-vscode#331] opened 2021-12-24 17:54 UTC
It seems it works only with arrays and strings autosuggesing `Js.Array2` and `Js.String2`, does not work with locally defined functions.

![image](https://user-images.githubusercontent.com/8079999/147367667-b171276c-9cda-4275-9b49-b8333c917a66.png)

![image](https://user-images.githubusercontent.com/8079999/147367690-50b25491-6f5c-4445-b1f8-1f839ec4baae.png)

**Comment by cristianoc** [comment] 2021-12-24 18:07
pipe auto completion is designed to work on types defined in a module, not on locally defined values

The analogue would be a local module defining a type t, then pipe will autocomplete on values of type t, by suggesting arbitrary functions defined in the module.

( a few things like strings and arrays are hard coded, and complete using the standard library)

**Comment by cristianoc** [comment] 2021-12-24 18:11
In other words, pipe autocomplete is designed to support data types defined in a module, where all functions take that type as first argument.

**Comment by Mng12345** [comment] 2021-12-30 06:11
@cristianoc it is hard to keep all the functions in mind, It would be happy when coding with pipe operator if the auto complete can work on functions defined outside module

**Comment by zth** [comment] 2022-05-05 13:18
Closing this for now, as it's working as intended right now (although it can of course be discussed how generalized pipe completion should be).

**Closed by zth** 2022-05-05 13:18 UTC

**Comment by Mng12345** [comment] 2022-05-06 01:19
Great work!!
