### ISSUE TITLE
Publish extension on open-vsx.org

### ISSUE THREAD

**Issue by Minnozz** [rescript-lang/rescript-vscode#226] opened 2021-05-06 13:17 UTC
Hi,

I use the editor [Onivim 2](https://onivim.io/), which uses VScode extensions published on the [Open VSX Registry](https://open-vsx.org/).

This plugin is [currently available there](https://open-vsx.org/extension/chenglou92/rescript-vscode), although it is currently published by the `open-vsx` account and not the latest version.

Would you consider publishing this extension on the Open VSX Registry yourself?

**Comment by chenglou** [comment] 2021-05-07 07:47
Hey! Sorry, this is a duplicate of #31. We won't do this for now.

**Closed by chenglou** 2021-05-07 07:47 UTC
