### ISSUE TITLE
Another autocompelte lost case.

### ISSUE THREAD

**Issue by Mng12345** [rescript-lang/rescript-vscode#416] opened 2022-05-12 08:38 UTC
environment: win10 x64 rescript-vscode 1.3.0 16GB RAM 8 cpu core.
![mnggiflab-output-compressed (10)](https://user-images.githubusercontent.com/21278900/168028275-f23de33b-01ef-4fd4-b2f7-7975d2e4c452.gif)
As the screen-recording gif, the autocomplete of record's field and function call is lost in \`${}\`, and it is very slow of autocomplete in JSX.

**Comment by cristianoc** [comment] 2022-05-12 15:16
@Mng12345 thanks for the report!
Would you try again with the .vsix from CI: https://github.com/rescript-lang/rescript-vscode/actions/runs/2314286376

**Comment by Mng12345** [comment] 2022-05-13 03:08
@cristianoc thanks for your great work! I have tryed this .vsix, it solved the problem, but the autocompelte is just too slow as before, it taskes almost 5s to get autocompelte.

**Comment by Mng12345** [comment] 2022-05-13 04:51
![mnggiflab-output-compressed (11)](https://user-images.githubusercontent.com/21278900/168213186-4eb30df0-c602-4bce-8e06-f26b01585d21.gif)
Emm, there is a another case in template expression.
The autocomplete is not worked in template expression in a function body

**Comment by cristianoc** [comment] 2022-05-13 05:37
> ![mnggiflab-output-compressed (11)](https://user-images.githubusercontent.com/21278900/168213186-4eb30df0-c602-4bce-8e06-f26b01585d21.gif)
> Emm, there is a another case in template expression.
> The autocomplete is not worked in template expression in a function body

That looks like viscose's making: if you explicitly ask for a completion (ctrl space) it should work.

**Comment by cristianoc** [comment] 2022-05-13 05:40
For the slow autocomplete, that needs to be looked into separately in order to reproduce.

I'd need a little more info on where it happens. Empty project? Empty file? Inside jsx? What dependencies? Everywhere? Etc.
To narrow down what's causing it so there's more chance to reproduce.

**Comment by Mng12345** [comment] 2022-05-13 07:16
The autocomplete is very fast in empty project, but my project is just only 20000+ lines of rescript(not including dependencies), it takes atleast 5s to get the autocomplete &#x1F630;
The dependencies is below:
![image](https://user-images.githubusercontent.com/21278900/168231270-92b67dec-f3ed-448d-a1ac-5216aded5ff6.png)

**Comment by zth** [comment] 2022-05-13 07:23
Hmm, I wonder if this might be a windows issue or something similar...? I have a 132k loc project where completing JSX props (and any autocomplete) is instant (in general, there's the odd slow response, but that does not happen often).

@Mng12345 is it the same in all files? Always as slow, no matter where you complete?

**Comment by Mng12345** [comment] 2022-05-13 07:56
@zth May be, the autocomplete is very slow in any file or any position of my project, and the rescript build -w process is also very slow. &#x1F602;
![image](https://user-images.githubusercontent.com/21278900/168237453-3eae3f6c-273c-4b56-84b4-97c797f45e48.png)

**Comment by zth** [comment] 2022-05-18 08:17
Closing this as the original issue is resoled, and I've seen @Mng12345 you've opened other issues for the compiler speed.

**Closed by zth** 2022-05-18 08:17 UTC

**Comment by Mng12345** [comment] 2022-05-18 08:20
> Closing this as the original issue is resolved, and I've seen @Mng12345 you've opened other issues for the compiler speed.

Yes.

**Comment by dkirchhof** [comment] 2022-05-20 18:07
I tried the vsix from above and still don't get any auto completions. Doesn't matter if i want to insert a let binding from the same file / module or from modules in other files.
Tried it first in neovim, then in vscodium (on a linux machine).
